version: 2.1
orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    executor:
      name: android/android-machine
      tag: "29"  # As an example, use a specific SDK version tag
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "gradle-wrapper.properties" }}
      - android/run-tests:
          test-command: ./gradlew lint testDebug --continue
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-29;google_apis;x86
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "gradle-wrapper.properties" }}

workflows:
  sample:
    jobs:
      - build-and-test
